import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    welcome: "Welcome",
    smartFarming: "Smart Farming System",
    chooseLanguage: "Choose your language",
    chooseLanguageHint: "Select a language to continue to your farming dashboard.",
    english: "English",
    tamil: "தமிழ்",
    continue: "Continue",
    dashboard: "Dashboard",
    dashboardHero: "A clearer view of your farm, every day.",
    dashboardIntro: "Turn soil, weather and plant signals into practical next steps.",
    farmAnalysis: "Farm Analysis",
    farmAnalysisDesc: "Check whether your soil and weather conditions are suitable for the crop.",
    plantGrowth: "Plant Growth Monitoring",
    plantGrowthDesc: "Compare your plant's current height with its expected growth.",
    weather: "Weather Advisory",
    weatherDesc: "View live weather conditions and possible crop risks for your district.",
    disease: "Disease Detection",
    diseaseDesc: "Upload a clear leaf photo to identify diseases and get treatment advice.",
    yield: "Yield Prediction",
    yieldDesc: "Estimate crop yield using your farm, soil, and weather details.",
    farmTitle: "Farm Analysis",
    district: "District",
    sowingMonth: "Sowing month",
    soilType: "Soil type",
    nitrogen: "Nitrogen",
    phosphorus: "Phosphorus",
    potassium: "Potassium",
    soilPh: "Soil pH",
    rainfall: "Rainfall",
    humidity: "Humidity",
    analyzeFarm: "Analyze farm",
    analyzing: "Analyzing...",
    positiveFactors: "Positive factors",
    issuesFound: "Issues found",
    recommendation: "Recommendation",
    suitable: "Suitable",
    notSuitable: "Not suitable",
    waterRequired: "Water required",
    fertilizerUsed: "Fertilizer used",
    example: "Example",
    unitKgPerAcre: "kg/acre",
    unitMm: "mm",
    unitPercent: "%",
    unitAcres: "acres",
    unitPh: "pH",
    growthTitle: "Smart Plant Growth Monitoring",
    daysAfterPlanting: "Days after planting (example: 30)",
    temperature: "Temperature in °C (example: 28)",
    soilMoisture: "Soil moisture in % (example: 55)",
    waterLevel: "Water level in litres (example: 20)",
    actualHeight: "Current plant height in cm (example: 18)",
    analyzeGrowth: "Analyze growth",
    predicting: "Predicting...",
    expectedGrowth: "Expected growth",
    actualGrowth: "Current growth",
    status: "Status",
    growthAnalysis: "Growth analysis",
    improve: "How to improve",
    maintain: "How to maintain",
    weatherTitle: "Smart Plant Risk Monitoring",
    enterDistrict: "Enter your district (example: Salem)",
    analyzeRisk: "Check plant risk",
    analyzingWeather: "Checking weather...",
    fetchingWeather: "Fetching live weather and checking plant risks...",
    districtResult: "District",
    windSpeed: "Wind speed",
    riskAnalysis: "Plant risk analysis",
    riskLevel: "Risk level",
    impact: "Impact",
    prevention: "Prevention",
    noRiskData: "No plant risk data available",
    yieldTitle: "Smart Farm Yield Analysis",
    farmArea: "Farm area in acres (example: 2)",
    selectDistrict: "Choose your district",
    selectSeason: "Choose the season",
    selectPesticide: "Choose the pesticide used",
    selectFertilizer: "Choose the fertilizer used",
    predictYield: "Predict yield",
    whyYield: "Why this yield?",
    increaseYield: "How to increase yield in future",
    expectedYield: "Expected yield",
    yieldLevel: "Yield level",
    diseaseTitle: "Leaf Disease Detection",
    uploadHint: "Upload a clear photo of a leaf",
    dragImage: "Drag a leaf photo here",
    browse: "or click to choose a photo",
    reset: "Reset",
    uploadDetect: "Upload and detect",
    diseaseLabel: "Disease",
    cause: "Cause",
    treatment: "Treatment",
    fertilizer: "Fertilizer",
    organicPrevention: "Organic prevention",
    loginRequired: "Please login to continue",
    errorFetchingWeather: "Unable to fetch weather data",
    serverError: "Unable to connect to the server",
  },
  ta: {
    welcome: "வரவேற்கிறோம்",
    smartFarming: "ஸ்மார்ட் விவசாய அமைப்பு",
    chooseLanguage: "மொழியைத் தேர்வு செய்யுங்கள்",
    chooseLanguageHint: "விவசாய டாஷ்போர்டுக்குச் செல்ல உங்கள் மொழியைத் தேர்வு செய்யுங்கள்.",
    english: "English",
    tamil: "தமிழ்",
    continue: "தொடரவும்",
    dashboard: "முகப்பு",
    dashboardHero: "ஒவ்வொரு நாளும் உங்கள் பண்ணையை தெளிவாகப் புரிந்துகொள்ளுங்கள்.",
    dashboardIntro: "மண், வானிலை மற்றும் செடி தகவல்களை நடைமுறை முடிவுகளாக மாற்றுங்கள்.",
    farmAnalysis: "பண்ணை ஆய்வு",
    farmAnalysisDesc: "உங்கள் மண் மற்றும் வானிலை பயிருக்கு ஏற்றதா என்பதைப் பாருங்கள்.",
    plantGrowth: "செடி வளர்ச்சி கண்காணிப்பு",
    plantGrowthDesc: "செடியின் தற்போதைய உயரத்தை எதிர்பார்க்கப்படும் வளர்ச்சியுடன் ஒப்பிடுங்கள்.",
    weather: "வானிலை ஆலோசனை",
    weatherDesc: "உங்கள் மாவட்டத்தின் நேரடி வானிலை மற்றும் பயிர் ஆபத்துகளைப் பாருங்கள்.",
    disease: "நோய் கண்டறிதல்",
    diseaseDesc: "தெளிவான இலைப் புகைப்படத்தை பதிவேற்றி நோய் மற்றும் சிகிச்சையை அறியுங்கள்.",
    yield: "மகசூல் கணிப்பு",
    yieldDesc: "பண்ணை, மண் மற்றும் வானிலை விவரங்களை வைத்து மகசூலை கணிக்கவும்.",
    farmTitle: "பண்ணை ஆய்வு",
    district: "மாவட்டம்",
    sowingMonth: "விதைத்த மாதம்",
    soilType: "மண் வகை",
    nitrogen: "நைட்ரஜன்",
    phosphorus: "பாஸ்பரஸ்",
    potassium: "பொட்டாசியம்",
    soilPh: "மண் pH",
    rainfall: "மழையளவு",
    humidity: "ஈரப்பதம்",
    analyzeFarm: "பண்ணையை ஆய்வு செய்க",
    analyzing: "ஆய்வு நடக்கிறது...",
    positiveFactors: "சாதகமான காரணிகள்",
    issuesFound: "கண்டறியப்பட்ட சிக்கல்கள்",
    recommendation: "பரிந்துரை",
    suitable: "ஏற்றது",
    notSuitable: "ஏற்றதல்ல",
    waterRequired: "தேவையான நீர்",
    fertilizerUsed: "பயன்படுத்திய உரம்",
    example: "உதாரணம்",
    unitKgPerAcre: "கிலோ/ஏக்கர்",
    unitMm: "மி.மீ.",
    unitPercent: "%",
    unitAcres: "ஏக்கர்",
    unitPh: "pH",
    growthTitle: "ஸ்மார்ட் செடி வளர்ச்சி கண்காணிப்பு",
    daysAfterPlanting: "நட்ட பின் நாட்கள் (உதாரணம்: 30)",
    temperature: "வெப்பநிலை °C (உதாரணம்: 28)",
    soilMoisture: "மண் ஈரப்பதம் % (உதாரணம்: 55)",
    waterLevel: "நீர் அளவு லிட்டரில் (உதாரணம்: 20)",
    actualHeight: "செடியின் தற்போதைய உயரம் செ.மீ. (உதாரணம்: 18)",
    analyzeGrowth: "வளர்ச்சியை ஆய்வு செய்க",
    predicting: "கணிக்கிறது...",
    expectedGrowth: "எதிர்பார்க்கப்படும் வளர்ச்சி",
    actualGrowth: "தற்போதைய வளர்ச்சி",
    status: "நிலை",
    growthAnalysis: "வளர்ச்சி ஆய்வு",
    improve: "மேம்படுத்துவது எப்படி",
    maintain: "பராமரிப்பது எப்படி",
    weatherTitle: "ஸ்மார்ட் செடி ஆபத்து கண்காணிப்பு",
    enterDistrict: "உங்கள் மாவட்டத்தை உள்ளிடவும் (உதாரணம்: சேலம்)",
    analyzeRisk: "செடி ஆபத்தைப் பார்க்கவும்",
    analyzingWeather: "வானிலை பார்க்கிறது...",
    fetchingWeather: "நேரடி வானிலையைப் பெற்று செடி ஆபத்துகளைப் பார்க்கிறது...",
    districtResult: "மாவட்டம்",
    windSpeed: "காற்றின் வேகம்",
    riskAnalysis: "செடி ஆபத்து ஆய்வு",
    riskLevel: "ஆபத்து நிலை",
    impact: "பாதிப்பு",
    prevention: "தடுப்பு",
    noRiskData: "செடி ஆபத்து தகவல் இல்லை",
    yieldTitle: "ஸ்மார்ட் பண்ணை மகசூல் ஆய்வு",
    farmArea: "பண்ணை பரப்பு ஏக்கரில் (உதாரணம்: 2)",
    selectDistrict: "உங்கள் மாவட்டத்தைத் தேர்வு செய்யவும்",
    selectSeason: "பருவத்தைத் தேர்வு செய்யவும்",
    selectPesticide: "பயன்படுத்திய பூச்சிக்கொல்லியைத் தேர்வு செய்யவும்",
    selectFertilizer: "பயன்படுத்திய உரத்தைத் தேர்வு செய்யவும்",
    predictYield: "மகசூலை கணிக்கவும்",
    whyYield: "இந்த மகசூலுக்கான காரணம்",
    increaseYield: "எதிர்காலத்தில் மகசூலை அதிகரிப்பது எப்படி",
    expectedYield: "எதிர்பார்க்கப்படும் மகசூல்",
    yieldLevel: "மகசூல் நிலை",
    diseaseTitle: "இலை நோய் கண்டறிதல்",
    uploadHint: "தெளிவான இலைப் புகைப்படத்தை பதிவேற்றவும்",
    dragImage: "இலைப் புகைப்படத்தை இங்கே இழுக்கவும்",
    browse: "அல்லது புகைப்படத்தைத் தேர்வு செய்ய கிளிக் செய்யவும்",
    reset: "மீட்டமை",
    uploadDetect: "பதிவேற்றி கண்டறியவும்",
    diseaseLabel: "நோய்",
    cause: "காரணம்",
    treatment: "சிகிச்சை",
    fertilizer: "உரம்",
    organicPrevention: "இயற்கை தடுப்பு",
    loginRequired: "தொடர முதலில் உள்நுழையவும்",
    errorFetchingWeather: "வானிலை தகவலைப் பெற முடியவில்லை",
    serverError: "சர்வரைத் தொடர்புகொள்ள முடியவில்லை",
  },
};

const backendTranslations = {
  "Below Standard": "தரத்திற்குக் குறைவு",
  "Excellent Growth": "மிகச் சிறந்த வளர்ச்சி",
  "Healthy Growth": "ஆரோக்கியமான வளர்ச்சி",
  "High Yield": "அதிக மகசூல்",
  "Moderate Yield": "மிதமான மகசூல்",
  "Low Yield": "குறைந்த மகசூல்",
  "Heat stress": "வெப்ப அழுத்தம்",
  "Waterlogging": "நீர் தேக்கம்",
  "Fungal disease": "பூஞ்சை நோய்",
  "No significant risk": "குறிப்பிடத்தக்க ஆபத்து இல்லை",
  "High temperature can stress crops.": "அதிக வெப்பநிலை பயிர்களுக்கு அழுத்தத்தை ஏற்படுத்தும்.",
  "Use shade, irrigation and mulch": "நிழல், நீர்ப்பாசனம் மற்றும் மூடாக்கு பயன்படுத்தவும்",
  "Excessive rain can cause root rot.": "அதிக மழை வேர் அழுகலை ஏற்படுத்தும்.",
  "Improve drainage and reduce irrigation": "வடிகாலமைப்பை மேம்படுத்தி நீர்ப்பாசனத்தை குறைக்கவும்",
  "High humidity can increase fungal risk.": "அதிக ஈரப்பதம் பூஞ்சை நோய் அபாயத்தை அதிகரிக்கும்.",
  "Use preventive sprays and improve airflow": "தடுப்பு தெளிப்புகளைப் பயன்படுத்தி காற்றோட்டத்தை மேம்படுத்தவும்",
  "Weather conditions are currently favorable.": "தற்போதைய வானிலை நிலைமைகள் சாதகமாக உள்ளன.",
  "Continue regular monitoring and maintain good farm practices.": "தொடர்ந்து கண்காணித்து நல்ல பண்ணை நடைமுறைகளைப் பின்பற்றவும்.",
  "High": "அதிகம்",
  "Medium": "நடுத்தரம்",
  "Low": "குறைவு",
  "Maintain balance": "சமநிலையைப் பராமரிக்கவும்",
  "Neem oil": "வேப்ப எண்ணெய்",
  "Neem Oil": "வேப்ப எண்ணெய்",
  "Summer": "கோடை",
  "Winter": "குளிர்காலம்",
  "Spring": "வசந்த காலம்",
  "Autumn": "இலையுதிர் காலம்",
  "Spinosad": "ஸ்பினோசாட்",
  "Imidacloprid": "இமிடாக்ளோபிரிட்",
  "Chlorpyrifos": "குளோர்பைரிஃபாஸ்",
  "Biopesticide": "உயிரியல் பூச்சிக்கொல்லி",
  "Azadirachtin": "அசாடிராக்டின்",
  "Beauveria bassiana": "பியூவேரியா பாசியானா",
  "Emamectin Benzoate": "எமாமெக்டின் பென்சோயேட்",
  "Lambda Cyhalothrin": "லாம்டா சைஹலோத்ரின்",
  "Fipronil": "ஃபிப்ரோனில்",
  "Carbaryl": "கார்பரில்",
  "Urea": "யூரியா",
  "DAP": "டிஏபி",
  "NPK": "என்.பி.கே.",
  "Organic Compost": "இயற்கை உரக்கழிவு",
  "Vermicompost": "மண்புழு உரம்",
  "Potash": "பொட்டாஷ்",
  "Single Super Phosphate": "சிங்கிள் சூப்பர் பாஸ்பேட்",
  "Ammonium Sulphate": "அமோனியம் சல்பேட்",
  "Bone Meal": "எலும்புத் தூள் உரம்",
  "Farmyard Manure": "பண்ணை எரு",
  "Neem Cake": "வேப்பங்கொட்டை உரம்",
  "Micronutrient Mix": "நுண்ணூட்டச்சத்து கலவை",
  "Optimal temperature supported eggplant growth": "சரியான வெப்பநிலை கத்தரிக்காய் வளர்ச்சிக்கு உதவியது",
  "Humidity supported healthy plant growth": "ஈரப்பதம் ஆரோக்கியமான செடி வளர்ச்சிக்கு உதவியது",
  "Adequate rainfall improved soil moisture": "போதுமான மழை மண் ஈரப்பதத்தை மேம்படுத்தியது",
  "Soil pH suitable for nutrient absorption": "மண் pH சத்துக்களை உறிஞ்சுவதற்கு ஏற்றது",
  "Nitrogen level supported vegetative growth": "நைட்ரஜன் அளவு இலை வளர்ச்சிக்கு உதவியது",
  "Season favorable for eggplant cultivation": "பருவம் கத்தரிக்காய் சாகுபடிக்கு ஏற்றது",
  "Fertilizer improved crop productivity": "உரம் பயிர் உற்பத்தியை மேம்படுத்தியது",
  "Pest control improved plant health": "பூச்சிக் கட்டுப்பாடு செடியின் ஆரோக்கியத்தை மேம்படுத்தியது",
  "Farm conditions are highly favorable": "பண்ணை நிலைமைகள் மிகவும் சாதகமாக உள்ளன",
  "Improve irrigation and fertilizer management": "நீர்ப்பாசனம் மற்றும் உர மேலாண்மையை மேம்படுத்துங்கள்",
  "Improve soil fertility and pest management": "மண் வளம் மற்றும் பூச்சி மேலாண்மையை மேம்படுத்துங்கள்",
  "Info not available": "தகவல் கிடைக்கவில்லை",
  "Try better image": "தெளிவான புகைப்படத்தை முயற்சிக்கவும்",
  "Healthy Leaf": "ஆரோக்கியமான இலை",
  "Leaf Spot Disease": "இலைப் புள்ளி நோய்",
  "Mosaic Virus Disease": "மொசைக் வைரஸ் நோய்",
  "Wilt Disease": "வாடல் நோய்",
  "White Mold Disease": "வெள்ளை பூஞ்சை நோய்",
  "Small Leaf Disease": "சிற்றிலை நோய்",
  "Insect Pest Disease": "பூச்சி தாக்குதல் நோய்",
  "High temperature may reduce yield, use mulching": "அதிக வெப்பநிலை மகசூலைக் குறைக்கலாம்; மூடாக்கைப் பயன்படுத்தவும்",
  "Low temperature slowed growth": "குறைந்த வெப்பநிலை வளர்ச்சியைத் தாமதப்படுத்தியது",
  "Maintain humidity between 55% - 75%": "ஈரப்பதத்தை 55% முதல் 75% வரை பராமரிக்கவும்",
  "Increase irrigation for better yield": "சிறந்த மகசூலுக்கு நீர்ப்பாசனத்தை அதிகரிக்கவும்",
  "Adjust soil pH using lime or organic compost": "சுண்ணாம்பு அல்லது இயற்கை உரக்கழிவைப் பயன்படுத்தி மண் pH-ஐ சரிசெய்யவும்",
  "Apply nitrogen fertilizer": "நைட்ரஜன் உரத்தைப் பயன்படுத்தவும்",
  "Summer or Spring season gives better yield": "கோடை அல்லது வசந்த காலத்தில் சிறந்த மகசூல் கிடைக்கும்",
  "Use NPK or organic fertilizers": "என்.பி.கே. அல்லது இயற்கை உரங்களைப் பயன்படுத்தவும்",
  "Use eco-friendly pest control": "சுற்றுச்சூழலுக்கு ஏற்ற பூச்சிக் கட்டுப்பாட்டு முறையைப் பயன்படுத்தவும்",
  "Large cultivation area supports better production": "பெரிய சாகுபடி பரப்பு சிறந்த உற்பத்திக்கு உதவும்",
  "Increase cultivation area size for higher yield": "அதிக மகசூலுக்கு சாகுபடி பரப்பை அதிகரிக்கவும்",
  "Growth conditions are normal": "வளர்ச்சி நிலைமைகள் இயல்பாக உள்ளன",
  "Maintain fertilizer schedule": "உரமிடும் அட்டவணையைப் பராமரிக்கவும்",
  "Good soil moisture supported root growth": "நல்ல மண் ஈரப்பதம் வேர் வளர்ச்சிக்கு உதவியது",
  "Adequate irrigation improved growth": "போதுமான நீர்ப்பாசனம் வளர்ச்சியை மேம்படுத்தியது",
  "Favorable environmental conditions supported growth": "சாதகமான சுற்றுச்சூழல் நிலைமைகள் வளர்ச்சிக்கு உதவின",
  "Infestation by aphids, mites, or whiteflies.": "அசுவினி, சிலந்திப் பூச்சி அல்லது வெள்ளை ஈ தாக்குதல்.",
  "Apply insecticides like Imidacloprid.": "இமிடாக்ளோபிரிட் போன்ற பூச்சிக்கொல்லிகளைப் பயன்படுத்தவும்.",
  "Nitrogen-rich fertilizer to boost recovery.": "மீட்சியை மேம்படுத்த நைட்ரஜன் நிறைந்த உரத்தைப் பயன்படுத்தவும்.",
  "Neem oil spray every 5 days.": "5 நாட்களுக்கு ஒருமுறை வேப்ப எண்ணெய் தெளிக்கவும்.",
  "Soil-borne bacteria or fungi.": "மண்ணில் உள்ள பாக்டீரியா அல்லது பூஞ்சை.",
  "Use resistant varieties and soil treatment.": "எதிர்ப்புத் திறன் கொண்ட வகைகள் மற்றும் மண் சிகிச்சையைப் பயன்படுத்தவும்.",
  "Potassium-rich fertilizer.": "பொட்டாசியம் நிறைந்த உரத்தைப் பயன்படுத்தவும்.",
  "Fungal infection due to high humidity.": "அதிக ஈரப்பதத்தால் ஏற்படும் பூஞ்சை தொற்று.",
  "Spray Mancozeb or Copper fungicide.": "மான்கோசெப் அல்லது காப்பர் பூஞ்சைக்கொல்லியைத் தெளிக்கவும்.",
  "Balanced NPK fertilizer.": "சமநிலையான என்.பி.கே. உரத்தைப் பயன்படுத்தவும்.",
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("smart-farming-language") || "en");

  const chooseLanguage = (nextLanguage) => {
    localStorage.setItem("smart-farming-language", nextLanguage);
    setLanguage(nextLanguage);
  };

  const t = (key) => translations[language][key] || translations.en[key] || key;
  const translateBackend = (value) => {
    if (language !== "ta" || typeof value !== "string") return value;
    if (backendTranslations[value]) return backendTranslations[value];
    return value
      .replace("Infestation by aphids, mites, or whiteflies", "அசுவினி, சிலந்திப் பூச்சி அல்லது வெள்ளை ஈ தாக்குதல்")
      .replace("Fungal infection due to high humidity", "அதிக ஈரப்பதத்தால் ஏற்படும் பூஞ்சை தொற்று")
      .replace("Fungal infection in moist conditions", "ஈரமான சூழலால் ஏற்படும் பூஞ்சை தொற்று")
      .replace("Soil-borne bacteria or fungi", "மண்ணில் உள்ள பாக்டீரியா அல்லது பூஞ்சை")
      .replace("Virus spread by aphids", "அசுவினியால் பரவும் வைரஸ்")
      .replace("Common in rainy season", "மழைக்காலத்தில் பொதுவாக காணப்படும்")
      .replace("Mostly affects young plants", "இளம் செடிகளை அதிகம் பாதிக்கும்")
      .replace("Spreads rapidly in humid weather", "ஈரமான வானிலையில் வேகமாக பரவும்")
      .replace("Follow recommended dosage", "பரிந்துரைக்கப்பட்ட அளவைப் பின்பற்றவும்")
      .replace("Repeat every 7 days", "7 நாட்களுக்கு ஒருமுறை மீண்டும் பயன்படுத்தவும்")
      .replace("Use after irrigation", "நீர்ப்பாசனத்திற்குப் பிறகு பயன்படுத்தவும்")
      .replace("Apply weekly", "வாரத்திற்கு ஒருமுறை பயன்படுத்தவும்")
      .replace("Apply regularly", "தொடர்ந்து பயன்படுத்தவும்")
      .replace("during early morning", "அதிகாலை நேரத்தில்")
      .replace("Improve drainage", "வடிகாலமைப்பை மேம்படுத்தவும்")
      .replace("Eco-friendly method", "சுற்றுச்சூழலுக்கு ஏற்ற முறை")
      .replace("Neem oil or baking soda spray", "வேப்ப எண்ணெய் அல்லது பேக்கிங் சோடா தெளிப்பு")
      .replace("Nitrogen-rich", "நைட்ரஜன் நிறைந்த")
      .replace("Potassium-rich", "பொட்டாசியம் நிறைந்த")
      .replace("Apply", "பயன்படுத்தவும்")
      .replace("Use", "பயன்படுத்தவும்")
      .replace("Maintain", "பராமரிக்கவும்")
      .replace("Increase", "அதிகரிக்கவும்")
      .replace("Improve", "மேம்படுத்தவும்");
  };

  return <LanguageContext.Provider value={{ language, chooseLanguage, t, translateBackend }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
